# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fastResidopC1 <- function(A, B) {
    .Call(`_RUVprps_fastResidopC1`, A, B)
}

fastResidopC2 <- function(A, B) {
    .Call(`_RUVprps_fastResidopC2`, A, B)
}

fastResidopC1lQR <- function(A, B) {
    .Call(`_RUVprps_fastResidopC1lQR`, A, B)
}

matrixMult <- function(A, B) {
    .Call(`_RUVprps_matrixMult`, A, B)
}

matSubtraction <- function(A, B) {
    .Call(`_RUVprps_matSubtraction`, A, B)
}

matTranspose <- function(A) {
    .Call(`_RUVprps_matTranspose`, A)
}

matInverse <- function(A) {
    .Call(`_RUVprps_matInverse`, A)
}

