#' The RUV-III method with technical replicates or PRPS normalization.
#'
#' @author Ramyar Molania
#'
#' @references
#' * Molania R., ..., Speed, T. P., A new normalization for Nanostring nCounter gene expression data, Nucleic Acids Research,
#' 2019.
#' * Molania R., ..., Speed, T. P., Removing unwanted variation from large-scale RNA sequencing data with PRPS,
#' Nature Biotechnology, 2023
#'
#' @description
#' This function applies the RUV-III with technical replicates or PRPS on transcriptions data.
#'
#' @details
#' RUV-III normalization. Before we can describe the linear model underlying RUV-III, we need to introduce the m × m1
#' mapping matrix M connecting assays to distinct samples, which captures the pattern of replication in our assays. Here,
#' m is the number of assays, and m1 is the number of distinct samples being assayed. M(i,h) = 1if assay i is on sample
#' h and M(i,h) = 0 otherwise. Each row of M sums to 1, and the columns sum to the distinct sample replication numbers, the
#' elements of MTM. We also define an m1 × p design matrix X to capture the biological factor(s) of interest indexed by
#' sample rather than assay. There are no constraints on p; indeed, X could be the m1 × m1 identity matrix. Our goal
#' here is to remove unwanted variation, not to estimate regression parameters.
#' The linear model we use is: Y = 1μ + MXβ + Wα + ε
#' where the data Y = (yij)and unobserved errors ε = (εij)are m × n; the matrices X and M have just been defined; μ is
#' the 1 × n row of gene means; β is p × n; the matrix W whose columns capture the unwanted variation is m × k; and α
#' is k × n. 1 = 1m is the m × 1 column vector of 1s. Here, m = number of assays, n = number of genes and p is the
#' dimension of the wanted variation X and k that of the unwanted variation W. Assume that W⊥1. Also, we suppose that we
#' have a subset of nc of negative control genes whose m × nc submatrix Yc satisfies Yc = 1μc + Wαc + εc, where we have
#' assumed that βc = 0—that is, that there is no true association between these genes and the biology of interest.
#' The projection PM = M(M M) M replaces each entry yij of Y by the simple average of the entries yi′j over all i′ for
#' which M (i, h) = M (i′ , h) = 1—that is, over all i′ such that i′ and i label replicate assays of the same unique
#' sample (or pseudo-sample) labeled h. Write RM = I − PM for the corresponding residual projector. This is our source
#' of information on the unwanted variation that we will remove. If the replication is technical at some level, then RMY
#' mainly contains information about unwanted variation in the system after the technical replicates were created.
#' Depending on the study details, technical replicates could be created immediately beforethe assay was run, in parallel
#' with or immediately after sample was collected or somewhere in between. The earlier the creation of technical replicates,
#' the more unwanted variation will be captured in their differences. The use of pseudo-replicates of suitable pseudo-samples
#' enables us to start to deal with pre-technical unwanted variation. Write the spectral decomposition of RMYY RM = UDU ,
#' where U is an m × m orthogonal matrix and D is an m × n diagonal matrix with entries ordered from largest to smallest
#' eigenvalue. Let P1 be the orthogonal projection onto 1m. For a chosen k, 1 ≤ k ≤ m−m1,
#' I- Define αˆ(k) = U(k)TY, where U(k) is the first k columns of U
#' II- Estimate W by regressing the centered negative controls (I − P1)Yc on αˆ(k)T c
#' III-
#'
#' @param se.obj A SummarizedExperiment object.
#' @param assay.name Character. A character indicating the name of the assay in the SummarizedExperiment
#' object. The selected assay should be the one that has been used for PRPS and NCGs selection.
#' @param control.sample.types Character. A character the specifies the type of control samples to be used in RUV-III
#' normalization. The option are: `prps`, `tr` and both of these. Any specifies control samples must be created before using the
#' function. The default is set to `prps`. If it is set to `both`, both prps and technical replicate must be provided.
#' @param prps.type character. A character denoting which groups of the generated PRPS should be utilized
#' for normalization. The options include `supervised`, `unsupervised`, or `both`. When `supervised` is chosen, the function
#' employs the PRPS set(s) generated through supervised functions. Opting for 'unsupervised' utilizes the PRPS set(s)
#' created through unsupervised functions. If 'both' is selected, the function utilizes the PRPS set(s) generated by both
#' supervised and unsupervised functions. The default setting is 'supervised.'
#' @param prps.group.names Character. A character indicating the name of the PRPS group under the 'prps.type' slot.
#' @param prps.set.names Character. A character specifying the exact name of a PRPS set under the 'prps.group' name in the
#' supervised or unsupervised slots in the SummarizedExperiment object. The default is set to 'all'. This will select all
#' available PRPS sets for the specified 'prps.group'.
#' @param ncg.type character. A character indicating which groups of the computed NCGs should be used
#' for normalization. The options include `supervised`, `unsupervised`, `pre.selected` or a combination of theses options.
#' . When 'supervised' is chosen, the function employs the PRPS set(s) generated through supervised functions. Opting for
#' 'unsupervised' utilizes the PRPS set(s)
#' created through unsupervised functions. If 'both' is selected, the function utilizes the PRPS set(s) generated by both
#' supervised and unsupervised functions. The default setting is 'supervised.'
#' @param ncg.group.names character. A character indicating the name of the NCGs group under the 'prps.type' slot.
#' @param ncg.set.names character specifying the exact name of an NCG set under the 'ncg.group' name in the
#' 'supervised' or unsupervised slots in the SummarizedExperiment object. The default is set to 'all'. This will select
#' all available NCG sets for the specified 'ncg.group'.
#' @param technical.replicates Vector. A vector of sample names that contain at least a technical duplicate. The length of
#' the vector must be as similar as possible to the number of samples in the SummarizedExperiment object. The sample names
#' of each set of technical replicates must be the same. See the details for more information.
#' @param k Numeric. A numeric value or a vector of numeric values indicating the number of unwanted factors to be calculated
#' and used to remove unwanted variation from the data. If a vector is provided, the function applies the RUV-III method
#' for each individual value, up to a maximum of possible k values for each normalization. See the details for more
#' information.
#' @param apply.log Logical. Indicates whether to apply a log-transformation to the data, PRPS, or both. The default is
#' set to 'TRUE'.
#' @param data.to.log Character. A character specifying the data that must be log-transformed before applying
#' the RUV-III method. The options are 'assay', 'prps', 'both', or 'none'. Remember, both data and PRPS must be in log
#' scale before applying the RUV-III method.
#' @param pseudo.count Numeric. A numeric value as a pseudo count to be added to all measurements before log transformation.
#' The default is set to 1. Note, the current RUV-III method does not support NA or missing values.
#' @param eta character. Gene-wise (as opposed to sample-wise) covariates. These covariates are adjusted for by
#' RUV-1 before any further analysis proceeds. Can be either (1) a matrix with n columns, (2) a matrix with n rows, (3)
#' a data frame with n rows, (4) a vector or factor of length n, or (5) simply 1, for an intercept term.
#' @param include.intercept Logical. When eta is specified (not NULL) but does not already include an intercept term, this
#' will automatically include one.
#' @param return.w Logical. If 'TRUE', additional information including the W matrix of the RUV-III method is returned.
#' The default is set to 'TRUE'.
#' @param return.wa Logical. If 'TRUE', additional information including the Wa matrix of the RUV-III method is returned.
#' The default is set to 'TRUE'.
#' @param check.se.obj Logical. Indicates whether to assess the SummarizedExperiment object or not. The default is set
#' to 'TRUE'. Refer to the checkSeObj function for more details.
#' @param remove.na character. A character indicating whether to remove NA or missing values from the assays
#' or not. The options are assays' and 'none'. The default is "assays", so all the NA or missing values from the assay(s)
#' will be removed before
#' applying the RUV-III method. See the 'checkSeObj' function for more details.
#' @param save.se.obj Logical. Indicates whether to save the RUV-III-PRPS normalized data as new assay(s) in the
#' SummarizedExperiment object or to output them as a list. The default is set to 'TRUE'.
#' @param verbose Logical. If 'TRUE', shows the messages of different steps of the function.
#'
#' @return Either the SummarizedExperiment object containing the RUV-III normalized gene expression data as new assay(s)
#' or a list of the RUV-III normalized gene expression data set(s).
#'
#' @importFrom SummarizedExperiment SummarizedExperiment assay colData
#' @importFrom ruv replicate.matrix RUV1
#' @importFrom BiocSingular bsparam
#' @importFrom Matrix solve
#' @export

RUVIIIprps <- function(
        se.obj,
        assay.name,
        control.sample.types = 'prps',
        prps.type = 'supervised',
        prps.group.names,
        prps.set.names = 'all',
        ncg.type = 'supervised',
        ncg.group.names,
        ncg.set.names,
        technical.replicates = NULL,
        k = c(1:5),
        apply.log = TRUE,
        data.to.log = 'assay',
        pseudo.count = 1,
        eta = NULL,
        include.intercept = TRUE,
        return.w = TRUE,
        return.wa = FALSE,
        check.se.obj = TRUE,
        remove.na = 'none',
        save.se.obj = TRUE,
        verbose = TRUE
        ) {
    printColoredMessage(message = '------------The RUVIIIprps function starts:',
                        color = 'white',
                        verbose = verbose)
    # Checking the function inputs ####
    if (!is.vector(assay.name) | length(assay.name) > 1 | is.logical(assay.name) | assay.name == 'all'){
        stop('The "assay.name" must be the name of a data in the SummarizedExperiment object.')
    }
    if (!assay.name %in% names(assays(se.obj))){
        stop('The "assay.name" cannot be found in the SummarizedExperiment object.')
    }
    if (length(unique(colnames(se.obj))) != ncol(se.obj)){
        stop('The samples names of the SummarizedExperiment object are not all unique.')
    }
    if (is.logical(control.sample.types) | is.null(control.sample.types) | is.numeric(control.sample.types)){
        stop('The "control.sample.types" cannot be NULL, numeric or logical.')
    }
    if (length(control.sample.types) > 2){
        stop('The length of the "control.sample.types" cannot be more than 2.')
    }
    if (sum(control.sample.types %in% c("prps", "tr" )) != length(control.sample.types)){
        stop('The "control.sample.types" must be one of the "prps", "tr" or both of these.')
    }
    if (identical(control.sample.types, 'tr')){
        if (is.null(technical.replicates)){
            stop('The "technical.replicates" must be provided as the "control.sample.types" is set to "both".')
        }
        if (length(technical.replicates) != ncol(se.obj)){
            stop('The length of the "technical.replicate" must be the same as the length of the samples of the the SummarizedExperiment object.')
        }
        if (length(unique(technical.replicates)) == length(technical.replicates)){
            stop('The samples ids provided in "technical.replicates" are unique. There is no technical replicates.')
        }
    }

    if (identical(control.sample.types, 'prps') | length(control.sample.types) > 1){
        if (is.logical(prps.type) | is.null(prps.type)){
            stop('The "prps.type" must be one of the "supervised", "un.supervised" or "both".')
        }
        if (length(prps.type) > 1){
            stop('The "prps.type" must be one of the "supervised", "un.supervised" or "both".')
        }
        if (!prps.type %in% c('supervised', 'un.supervised', 'both')){
            stop('The "prps.type" must be one of the "supervised", "un.supervised" or "both".')
        }
        if (length(se.obj@metadata) == 0 | !'PRPS' %in% names(se.obj@metadata)){
            stop(paste0(
                'Any type of PRPS data cannot be found in the SummarizedExperiment object.',
                'Please make usre that you have created PRPS data and saved them in the SummarizedExperiment object.')
            )
        }
        if (prps.type == 'supervised'){
            if (!'supervised' %in% names(se.obj@metadata$PRPS)){
                stop('The "supervised" object does not exist in the PRPS slot of the metada of the SummarizedExperiment object.')
            }
            if (length(se.obj@metadata$PRPS$supervised) == 0){
                stop('The "supervised" object in the PRPS slot of the metadata of the SummarizedExperiment object does not contain any data.')
            }
            if (is.null(prps.group.names) | is.logical(prps.group.names)){
                stop('The "prps.group.names" can not be NULL or logical.')
            }
            if (length(prps.group.names) > 1){
                stop('The "prps.group.names" must be a single name of a prps group data.')
            }
            if (!prps.group.names %in% names(se.obj@metadata$PRPS$supervised)){
                stop('The "prps.group.names" cannot be found in the "supervised" part of th PRPS slot in the the metada of the SummarizedExperiment object.')
            }
            if (is.logical(prps.set.names) | is.null(prps.set.names)){
                stop('The "prps.set.names" cannot be logical or NULL.')
            }
            if (identical(prps.set.names, 'all')){
                supervised.prps.set.names <- names(se.obj@metadata$PRPS$supervised[[prps.group.names]])
            } else supervised.prps.set.names <- prps.set.names
            if (sum(supervised.prps.set.names %in% names(se.obj@metadata$PRPS$supervised[[prps.group.names]])) != length(supervised.prps.set.names)){
                stop('All or some of the "prps.set.names" cannot be found in the "supervised" part of th PRPS slot in the the metada of the SummarizedExperiment object.')
            }
            supervised.prps.group.name <- prps.group.names
        }
        if (prps.type == 'un.supervised'){
            if (!'un.supervised' %in% names(se.obj@metadata$PRPS)){
                stop('The "un.supervised" object does not exist in the PRPS slot of the metada of the SummarizedExperiment object.')
            }
            if (length(se.obj@metadata$PRPS$un.supervised) == 0){
                stop('The "un.supervised" object in the PRPS slot of the metadata of the SummarizedExperiment object does not contain any data.')
            }
            if (is.null(prps.group.names) | is.logical(prps.group.names)){
                stop('The "prps.group.names" can not be NULL or logical.')
            }
            if (length(prps.group.names) > 1){
                stop('The "prps.group.names" must be a single name of a prps group data.')
            }
            if (!prps.group.names %in% names(se.obj@metadata$PRPS$un.supervised)){
                stop('All or some of the "prps.group.names" cannot be found in the "un.supervised" part of th PRPS slot in the the metada of the SummarizedExperiment object.')
            }
            if (is.logical(prps.set.names) | is.null(prps.set.names)){
                stop('The "prps.set.names" cannot be logical or NULL.')
            }
            if (identical(prps.set.names, 'all')){
                unsupervised.prps.set.names <- names(se.obj@metadata$PRPS$un.supervised[[prps.group.names]])
            } else  unsupervised.prps.set.names <- prps.set.names
            if (sum(unsupervised.prps.set.names %in% names(se.obj@metadata$PRPS$un.supervised[[prps.group.names]])) != length(unsupervised.prps.set.names)){
                stop('All or some of the "prps.set.names" cannot be found in the "un.supervised" part of th PRPS slot in the the metada of the SummarizedExperiment object.')
            }
            unsupervised.prps.group.name <- prps.group.names
        }
        if (prps.type == 'both'){
            if (!'supervised' %in% names(se.obj@metadata$PRPS)){
                stop('The "supervised" object does not exist in the PRPS slot of the metada of the SummarizedExperiment object.')
            }
            if (length(se.obj@metadata$PRPS$supervised) == 0){
                stop('The "supervised" object in the PRPS slot of the metadata of the SummarizedExperiment object does not contain any data.')
            }
            if (!'un.supervised' %in% names(se.obj@metadata$PRPS)){
                stop('The "un.supervised" object does not exist in the PRPS slot of the metada of the SummarizedExperiment object.')
            }
            if (length(se.obj@metadata$PRPS$un.supervised) == 0){
                stop('The "un.supervised" object in the PRPS slot of the metadata of the SummarizedExperiment object does not contain any data.')
            }
            if (is.null(prps.group.names) | is.logical(prps.group.names)){
                stop('The "prps.group.names" can not be NULL or logical.')
            }
            if (sum(prps.group.names %in% names(se.obj@metadata$PRPS$supervised)) == 0){
                stop('Any "prps.group.names" cannot be found in the "supervised" object in the PRPS slot of the metadata of the SummarizedExperiment')
            }
            if (sum(prps.group.names %in% names(se.obj@metadata$PRPS$un.supervised)) == 0){
                stop('Any "prps.group.names" cannot be found in the "un.supervised" object in the PRPS slot of the metadata of the SummarizedExperiment')
            }
            supervised.prps.group.name <- prps.group.names[prps.group.names %in% names(se.obj@metadata$PRPS$supervised)]
            unsupervised.prps.group.name <- prps.group.names[prps.group.names %in% names(se.obj@metadata$PRPS$un.supervised)]
            if (is.null(names(se.obj@metadata$PRPS$un.supervised[[supervised.prps.group.name]]))){
                stop(' There is no any PRPS set names in the "supervised" object in the PRPS slot of the metadata of the SummarizedExperiment')
            }
            if (is.null(names(se.obj@metadata$PRPS$un.supervised[[unsupervised.prps.group.name]]))){
                stop(' There is no any PRPS set names in the "un.supervised" object in the PRPS slot of the metadata of the SummarizedExperiment')
            }
            all.prps.set.names <- c(
                names(se.obj@metadata$PRPS$supervised[[supervised.prps.group.name]]),
                names(se.obj@metadata$PRPS$un.supervised[[unsupervised.prps.group.name]])
                )
            if (identical(prps.set.names, 'all')){
                prps.set.names <- all.prps.set.names
            }
            if (sum(prps.set.names %in% all.prps.set.names) != length(all.prps.set.names)){
                stop('All or some of "all.prps.set.names" cannot be found in the "supervised" or" un.supervised" objects in the PRPS slot of the metadata of the SummarizedExperiment')
            }
        }
    }
    if (is.logical(ncg.type) | is.null(ncg.type) | is.numeric(ncg.type)){
        stop('The "ncg.type" cannot be NULL, numeric or logical.')
    }
    if (length(ncg.type) > 3){
        stop('The length of the "ncg.type" cannot be more than 3.')
    }
    if (sum(ncg.type %in% c("supervised", "un.supervised", "pre.selected",  "all.genes")) != length(ncg.type)){
        stop('The "ncg.type" must "supervised", "un.supervised", "pre.selected", "all.genes" or a combination of these.')
    }
    if (length(ncg.type) > 1 & 'all.genes' %in% ncg.type){
        stop('The "ncg.type" includes both "all.genes" and other options. The "ncg.type" can either "all.genes" or a or combination of other options.')
    }

    if (!identical(ncg.type, "all.genes")){
        if (!'NCG' %in% names(se.obj@metadata)){
            stop('The "NCG" object does not exist in the metada of the SummarizedExperiment object.')
        }
        if (isTRUE('supervised' %in%  ncg.type)){
            if (!'supervised' %in% names(se.obj@metadata$NCG)){
                stop('The supervised "NCG" object does not exist in the NCG slot of the metada of the SummarizedExperiment object.')
            }
            if (is.null(ncg.group.names) | is.logical(ncg.group.names)){
                stop('The "ncg.group.names" can not be NULL or logical.')
            }
            if (length(ncg.group.names) > 1){
                stop('The "ncg.group.names" must be a single name of a ncg group data.')
            }
            if (!ncg.group.names %in% names(se.obj@metadata$NCG$supervised)) {
                stop('The "supervised" object does not exist in the NCG groups slot of the metada of the SummarizedExperiment object.')
            }
            if (identical(ncg.set.names, 'all')){
                supervised.ncg.set.names <- names(se.obj@metadata$NCG$supervised[[ncg.group.names]])
            } else supervised.ncg.set.names <- ncg.set.names
            if (sum(supervised.ncg.set.names %in% names(se.obj@metadata$NCG$supervised[[ncg.group.names]])) != length(supervised.ncg.set.names)){
                stop('All or some of the "ncg.set.names" cannot be found in the "supervised" part of th NCG slot in the the metada of the SummarizedExperiment object.')
            }
            supervised.ncg.group.names <- ncg.group.names
        }
        if (isTRUE('un.supervised' %in%  ncg.type)){
            if (!'un.supervised' %in% names(se.obj@metadata$NCG)){
                stop('The un.supervised "NCG" object does not exist in the NCG slot of the metada of the SummarizedExperiment object.')
            }
            if (is.null(ncg.group.names) | is.logical(ncg.group.names)){
                stop('The "ncg.group.names" can not be NULL or logical.')
            }
            if (length(ncg.group.names) > 1){
                stop('The "ncg.group.names" must be a single name of a ncg group data.')
            }
            if (!ncg.group.names %in% names(se.obj@metadata$NCG$un.supervised)) {
                stop('The "un.supervised" object does not exist in the NCG groups slot of the metada of the SummarizedExperiment object.')
            }
            if (identical(ncg.set.names, 'all')){
                unsupervised.ncg.set.names <- names(se.obj@metadata$NCG$un.supervised[[ncg.group.names]])
            } else unsupervised.ncg.set.names <- ncg.set.names
            if (sum(unsupervised.ncg.set.names %in% names(se.obj@metadata$NCG$un.supervised[[ncg.group.names]])) != length(unsupervised.ncg.set.names)){
                stop('All or some of the "ncg.set.names" cannot be found in the "un.supervised" part of th NCG slot in the the metada of the SummarizedExperiment object.')
            }
            unsupervised.ncg.group.names <- ncg.group.names
        }
    }
    if (!is.numeric(k)){
        stop('The "k" must numeric value(s).')
    }
    if (min(k) <= 0){
        stop('k cannot be 0 or negative values.')
    }
    if (!is.logical(apply.log)){
        stop('The "apply.log" must be logical.')
    }
    if (!is.character(data.to.log) | length(data.to.log) > 1){
        stop('The "data.to.log" must be one of the "assay", "prps" or "both".')
    }
    if (!data.to.log %in% c("assay", "prps", "both")){
        stop('The "data.to.log" must be one of the "assay", "prps" or "both".')
    }
    if (!is.numeric(pseudo.count)){
        stop('The "pseudo.count" must a numeric value.')
    }
    if (pseudo.count <= 0){
        stop('The "pseudo.count" must be a positive numeric value.')
    }
    if (!is.logical(return.w)){
        stop('The "return.w" must be logical.')
    }
    if (!is.logical(check.se.obj)){
        stop('The "check.se.obj" must be logical.')
    }
    if (!is.logical(save.se.obj)){
        stop('The "save.se.obj" must be logical.')
    }
    if (!is.logical(verbose)){
        stop('The "verbose" must be logical.')
    }

    # Assessing the SummarizedExperiment object ####
    if (isTRUE(check.se.obj)) {
        se.obj <- checkSeObj(
            se.obj = se.obj,
            assay.names = assay.name,
            variables = NULL,
            remove.na = remove.na,
            verbose = verbose)
    }

    # Retrieving control samples ####
    printColoredMessage(
        message = '-- Retrieving and checking control samples data:',
        color = 'magenta',
        verbose = verbose
        )
    ## PRPS data ####
    if (identical(control.sample.types, 'prps') | length(control.sample.types) > 1){
        ### Retrieving PRPS data ####
        printColoredMessage(
            message = '- Obtaining the PRPS data from the SummarizedExperiment objec.',
            color = 'blue',
            verbose = verbose
            )
        #### Supervised PPRS data ####
        if (prps.type == 'supervised'){
            printColoredMessage(
                message = paste0(
                    '- The prps group "',
                    supervised.prps.group.name,
                    '" has ',
                    length(se.obj@metadata$PRPS$supervised[[supervised.prps.group.name]]),
                    ' PRPS group set(s).'),
                color = 'blue',
                verbose = verbose
                )
            prps.data <- lapply(
                supervised.prps.set.names,
                function(x) {
                    se.obj@metadata$PRPS$supervised[[supervised.prps.group.name]][[x]]$prps.data
                })
            names(prps.data) <- prps.set.names
        }
        #### Unsupervised PRPS data ####
        if (prps.type == 'un.supervised'){
            printColoredMessage(
                message = paste0(
                    '- The prps group "',
                    unsupervised.prps.group.name,
                    '" has ',
                    length(se.obj@metadata$PRPS$un.supervised[[unsupervised.prps.group.name]]),
                    ' PRPS sub_group(s).'),
                color = 'blue',
                verbose = verbose
                )
            prps.data <- lapply(
                unsupervised.prps.set.names,
                function(x) {
                    se.obj@metadata$PRPS$un.supervised[[unsupervised.prps.group.name]][[x]]$prps.data
                })
            names(prps.data) <- prps.set.names

        }
        #### Both supervised and unsupervised PRPS data ####
        if (prps.type == 'both'){
            if (is.null(prps.group.names)){
                prps.data <- c(
                    se.obj@metadata$PRPS$supervised,
                    se.obj@metadata$PRPS$un.supervised$prps.data
                )
            } else{
                prps.data.sup <- lapply(
                    prps.group.names,
                    function(x) se.obj@metadata$PRPS$supervised[[x]])
                names(prps.data.sup) <- prps.group.names
                prps.data.unsup <- lapply(
                    prps.group.names,
                    function(x) se.obj@metadata$PRPS$un.supervised[[x]])
                names(prps.data.unsup) <- prps.group.names
                prps.data <- c(prps.data.sup, prps.data.unsup)
                prps.data <- Filter(Negate(is.null), prps.data)
            }
            printColoredMessage(
                message = paste0(
                    length(prps.data),
                    ' supervised/unsupervised PRPS set(s) are found in the SummarizedExperiment object.'),
                color = 'blue',
                verbose = verbose
                )
        }
        ### Checking dimension and gene names in the prps data ####
        printColoredMessage(
            message = '-- Checking the row names and number of pseudo samples in the PRPS data:',
            color = 'blue',
            verbose = verbose
            )
        check.prps.data <- lapply(
            1:length(prps.data),
            function(x){
                if (nrow(se.obj) != nrow(prps.data[[x]]) ) {
                    stop('The number of genes between the SummarizedExperiment object and the prps data is not the same.')
                }
                if (isFALSE(all.equal(row.names(se.obj), row.names(prps.data[[x]]))) ) {
                    stop('The order of genes are not the same between the SummarizedExperiment object and the PRPS data.')
                }
                rep.samples <- findRepeatingPatterns(
                    vec = colnames(prps.data[[x]]),
                    n.repeat = 2
                )
                if (length(rep.samples) == 0) {
                    stop('The names of the columns in the "prps.data" are all unique.')
                } else if (isTRUE(length(rep.samples) != length(unique(colnames(prps.data[[x]]))))) {
                    stop('Some names of the columns in the "prps.data" are all unique.')
                }
            })
        if (length(prps.data) > 1){
            all.pairs <- combn(x = 1:length(prps.data), m = 2)
            m.out <- lapply(
                1:ncol(all.pairs),
                function(x){
                    common.names <- intersect(
                        colnames(prps.data[[all.pairs[1 ,x]]]),
                        colnames(prps.data[[all.pairs[2 ,x]]])
                        )
                    if (length(common.names) > 0){
                        stop('Different sets of PRPS have the same name, please check the PRPS creation steps.')
                    }
                })
        }
        printColoredMessage(
            message = '- The PRPS data has no issues.',
            color = 'blue',
            verbose = verbose
            )
        ## Merging all the PRPS data ####
        printColoredMessage(
            message = '-- Merging all the PPRS data:',
            color = 'blue',
            verbose = verbose
        )
        prps.data <- do.call(cbind, prps.data)
        printColoredMessage(
            message = paste0(
                '- The final PRPS data has: ',
                ncol(prps.data),
                ' pseudo-samples and ',
                length(findRepeatingPatterns(vec = colnames(prps.data), n.repeat = 2)),
                ' PRPS sets.'),
            color = 'blue',
            verbose = verbose
        )
    } else prps.data <- NULL

    ## Technical replicates ####
    if (identical(control.sample.types, 'tr') | length(control.sample.types) > 1){
        printColoredMessage(
            message = '-- Assessing technical replicates lables:',
            color = 'blue',
            verbose = verbose
            )
        rep.samples <- findRepeatingPatterns(
            vec = technical.replicates,
            n.repeat = 2
        )
        if (length(rep.samples) == 0){
            stop(paste0(
                'All the lables/sample ids provided by  "technical.replicates" are unique.',
                'Each set of technical replicates must have the same name within the set and be',
                'uniquely named compared to other samples.')
            )
        } else {
            printColoredMessage(
                message = paste0(
                    '- There is(are) ',
                    length(unique(rep.samples)),
                    ' sets of technical replicates in the data.'),
                color = 'blue',
                verbose = verbose
            )
        }
        initial.colnames <- colnames(se.obj)
        colnames(se.obj) <- technical.replicates
    }
    # Retrieving control genes ####
    printColoredMessage(
        message = '-- Retrieving NCGs in the SummarizedExperiment object',
        color = 'magenta',
        verbose = verbose
        )
    ## All genes as NCGs ####
    if (identical(ncg.type, 'all.genes')) {
        ncg.all.genes <- row.names(se.obj)
    } else ncg.all.genes <- NULL
    if (!identical(ncg.type, 'all.genes')){
        ## Supervised NCGs ####
        if ('supervised' %in% ncg.type ){
            if (sum(supervised.ncg.set.names %in% 'assessment.plot') == 1 ){
                if (!'ncg.set' %in% names(se.obj@metadata$NCG$supervised[[supervised.ncg.group.names]][['assessment.plot']])){
                    supervised.ncg.set.names <- supervised.ncg.set.names[!supervised.ncg.set.names %in% 'assessment.plot']
                }
            }
            printColoredMessage(
                message = paste0(
                    '- The supervised NCG group "',
                    supervised.ncg.group.names,
                    '" has ',
                    length(supervised.ncg.set.names),
                    ' NCG sub_group(s).'),
                color = 'blue',
                verbose = verbose
                )
            if (length(supervised.ncg.set.names) > 1){
                printColoredMessage(
                    message = '- The union of the NCGs sets will be used.',
                    color = 'blue',
                    verbose = verbose
                )
            }
            supervised.ncg <- lapply(
                supervised.ncg.set.names,
                function(x) se.obj@metadata$NCG$supervised[[supervised.ncg.group.names]][[x]]$ncg.set
            )
            names(supervised.ncg) <- supervised.ncg.set.names
            supervised.ncg <- do.call(cbind, supervised.ncg)
            supervised.ncg <- rowSums(supervised.ncg) != 0
            supervised.ncg <- row.names(se.obj)[supervised.ncg]
        } else supervised.ncg <- NULL

        ## Unsupervised NCGs ####
        if ('un.supervised' %in% ncg.type ){
            if (sum(unsupervised.ncg.set.names %in% 'assessment.plot') == 1 ){
                if (!'ncg.set' %in% names(se.obj@metadata$NCG$un.supervised[[unsupervised.ncg.group.names]][['assessment.plot']])){
                    unsupervised.ncg.set.names <- unsupervised.ncg.set.names[!unsupervised.ncg.set.names %in% 'assessment.plot']
                }
            }
            printColoredMessage(
                message = paste0(
                    '- The un supervised NCG group "',
                    unsupervised.ncg.group.names,
                    '" has ',
                    length(unsupervised.ncg.set.names),
                    ' NCG set.'),
                color = 'blue',
                verbose = verbose
            )
            if (length(unsupervised.ncg.set.names) > 1){
                printColoredMessage(
                    message = '- The union of the NCGs sets will be used.',
                    color = 'blue',
                    verbose = verbose
                )
            }
            unsupervised.ncg <- lapply(
                unsupervised.ncg.set.names,
                function(x) se.obj@metadata$NCG$un.supervised[[unsupervised.ncg.group.names]][[x]]$ncg.set
            )
            names(unsupervised.ncg) <- unsupervised.ncg.set.names
            unsupervised.ncg <- do.call(cbind, unsupervised.ncg)
            unsupervised.ncg <- rowSums(unsupervised.ncg) != 0
            unsupervised.ncg <- row.names(se.obj)[unsupervised.ncg]
        } else unsupervised.ncg <- NULL
        ## Pre selected NCGs ####
        if ('pre.selected' %in% ncg.type ){
            if (is.null(supervised.ncg.group.names)){
                ncg <- se.obj@metadata$NCG$pre.selected
            } else{
                pre.selected <- lapply(
                    supervised.ncg.group.names,
                    function(x) se.obj@metadata$NCG$pre.selected[[x]])
                names(ncg) <- supervised.ncg.group.names
            }
            printColoredMessage(
                message = paste0(
                    length(ncg),
                    ' supervised NCG set(s) are found in the SummarizedExperiment object.'),
                color = 'blue',
                verbose = verbose
                )
        } else pre.selected <- NULL
    }
    final.ncg <- c(supervised.ncg, unsupervised.ncg, pre.selected, ncg.all.genes)
    printColoredMessage(
        message = paste0(
            '- The final set of NCGs contains ',
            length(final.ncg),
            ' genes.'),
        color = 'blue',
        verbose = verbose
        )
    final.ncg <- row.names(se.obj) %in% final.ncg

    # Checking max k for each normalization ####
    printColoredMessage(
        message = '-- Checking the maximum possible k vlaue for RUV-III normalization:',
        color = 'magenta',
        verbose = verbose
        )
    control.assay <- findRepeatingPatterns(
        vec = c(colnames(prps.data), colnames(se.obj)),
        n.repeat = 2
        )
    max.k.values <- min(length(control.assay), sum(final.ncg))
    printColoredMessage(
        message = paste0(
            '- The maximum k for the curret control samples and NCGs is ',
            max.k.values,
            '.'),
        color = 'blue',
        verbose = verbose
        )

    # Finding possible number of runs of RUV-III ####
    printColoredMessage(
        message = '-- Possible runs of RUV-III based on the current parameters:',
        color = 'magenta',
        verbose = verbose
        )
    if (isTRUE(length(k) == 1)){
        if (max.k.values >= k){
            printColoredMessage(
                message = paste0(
                    '- The RUV-III will be performed with k = ',
                    k,
                    '.'),
                color = 'blue',
                verbose = verbose
                )
        } else if ( k > max.k.values ){
            printColoredMessage(
                message = '- Please note that the specified k value(s) exceeds the maximum allowable k value for the current PRPS data and NCGs',
                color = 'red',
                verbose = verbose
                )
            printColoredMessage(
                message = paste0(
                    '- The RUV-III will be performed with k = ',
                    max.k.values,
                    '.'),
                color = 'blue',
                verbose = verbose
                )
            k <- max.k.values
        }
    } else if (isTRUE(length(k) > 1)){
        if ( max.k.values >= max(k) ){
            printColoredMessage(
                message = paste0(
                    '- The RUV-III will be performed with k = ',
                    paste0(k, collapse = ','),
                    '.'),
                color = 'blue',
                verbose = verbose
                )
        } else if ( max(k) >  max.k.values){
            printColoredMessage(
                message = 'Please note, the maximum of specifed k values is greate than possible maximum k for the curret PRPS data and NCGs',
                color = 'red',
                verbose = verbose
                )
        }
        k <- k[ k <= max.k.values]
        printColoredMessage(
            message = paste0(
                '- The RUV-III will be performed with k = ',
                paste0(k, collapse = ','),
                '.'),
            color = 'blue',
            verbose = verbose
            )
    }
    printColoredMessage(
        message = paste0(
            '- In totall ',
            length(k),
            ' runs of RUV-III normalization will be performed'),
        color = 'blue',
        verbose = verbose)

    # Applying data transformation ####
    if (isTRUE(apply.log)){
        if (is.null(pseudo.count)) pseudo.count = 0
        printColoredMessage(
            message = '-- Applying data log transformation:',
            color = 'magenta',
            verbose = verbose
        )
        if (data.to.log == 'both') {
            printColoredMessage(
                message = paste(
                    'Applying log2 + ',
                    pseudo.count,
                    ' (pseudo.count) on both assay and prps data.'),
                color = 'blue',
                verbose = verbose
            )
            Y <- log2(assay(x = se.obj, i = assay.name) + pseudo.count)
            prps.data <- log2(prps.data + pseudo.count)
        } else if (data.to.log == 'assay') {
            printColoredMessage(
                message = paste0(
                    'Applying log2 + ',
                    pseudo.count,
                    ' (pseudo.count) on only assay.'),
                color = 'blue',
                verbose = verbose
            )
            Y <- log2(assay(x = se.obj, i = assay.name) + pseudo.count)
        } else if (data.to.log == 'prps') {
            printColoredMessage(
                message = paste(
                    'Applying log2 + ',
                    pseudo.count,
                    ' (pseudo.count) on only control samples.'),
                color = 'blue',
                verbose = verbose
            )
            prps.data <- log2(prps.data + pseudo.count)
        }
    } else if (isFALSE(apply.log)) {
        printColoredMessage(
            message = 'It seems both assay and PRPS are already log transformed.',
            color = 'blue',
            verbose = verbose
        )
        Y <- assay(x = se.obj, i = assay.name)
    }
    printColoredMessage(
        message = '** Note: please ensure that both the data and PRPS are log-transformed.',
        color = 'red',
        verbose = verbose
        )

    # RUVIII normalization ####
    printColoredMessage(
        message = '-- Applying the RUV-III method:',
        color = 'magenta',
        verbose = verbose
        )
    ## k > 1 ####
    if (length(k) > 1) {
        printColoredMessage(
            message = paste0(
                '- The length of k is more than 1.',
                ' Then, full alpha will be calculated for the maximum value of k.'),
            color = 'blue',
            verbose = verbose
        )
        printColoredMessage(
            message = '- Applying RUV-III for the maximum value of k.',
            color = 'orange',
            verbose = verbose
            )
        ### checking ncg ####
        ncg.set <- final.ncg
        ncg.logi <- rep(FALSE, nrow(se.obj))
        ncg.logi[ncg.set] <- TRUE
        ncg.set <- ncg.logi
        ## checking prps data ####
        prps.data <- prps.data
        k.vals <- k
        ## merging data and control samples ####
        Y <- t(cbind(Y, prps.data))
        if (is.data.frame(Y))
            Y <- data.matrix(Y)
        if (sum(is.na(Y)) > 0) {
            stop("The assay or PRPS data contains missing values. This is not supported.")
        } else if (sum(Y == Inf, na.rm = TRUE) + sum(Y == -Inf, na.rm = TRUE) > 0) {
            stop("The assay or PRPS data contains infinity values. This is not supported.")
        }
        ##  applying RUV1 on Y ####
        if (is.null(eta)){
            printColoredMessage(
                message = '- Applying RUV1 on the both data and control samples:',
                color = 'blue',
                verbose = verbose
            )
            Y <- ruv::RUV1(
                Y = Y,
                eta = eta,
                ctl = ncg.set,
                include.intercept = include.intercept
            )
        }
        ## standardizing the both ####
        printColoredMessage(
            message = '- Standardizing the both data and control samples.',
            color = 'blue',
            verbose = verbose
            )
        Y.stand <- scale(Y, center = TRUE, scale = FALSE)

        ## creating M matrix ####
        printColoredMessage(
            message = '- Creating the M martix (replication patterns).',
            color = 'blue',
            verbose = verbose
            )
        M <- replicate.matrix(row.names(Y))
        printColoredMessage(
            message = paste0(
                '- The M martix has ',
                nrow( M),
                ' rows and ',
                ncol(M),
                ' columns'),
            color = 'blue',
            verbose = verbose
            )

        ## applying a sanity check on M matrix ####
        printColoredMessage(
            message = '- Applying a sanity check on the M matrix.',
            color = 'blue',
            verbose = verbose
            )
        sum(rowSums(M) != 1)
        sum(colSums(M) == 1)
        if (nrow(M) == ncol(M)){
            stop('The numer of the columns and rows of the M matrix are the same, this is an issue.')
        }

        ## obtaining residuals from the control assays ####
        printColoredMessage(
            message = '- Obtaining residuals from the control samples data.',
            color = 'blue',
            verbose = verbose
            )
        # Y0 <- fastResidop2(Y, M)
        Y0 <- optimized_function(Y, M)
        ## applying svd on the residuals and the obtain alpha ####
        printColoredMessage(
            message = '- Applying SVD on the residuals to obtain full alpha.',
            color = 'blue',
            verbose = verbose
            )
        set.seed(22331)
        left.sing.value <- BiocSingular::runSVD(
            x = Y0,
            k = max(k.vals),
            BSPARAM = bsparam(),
            center = TRUE,
            scale = FALSE
            )$u
        alpha <- t(left.sing.value[, 1:max(k.vals), drop = FALSE]) %*% Y
        ac <- alpha[, ncg.set, drop = FALSE]
        ## obtaining W ####
        printColoredMessage(
            message = '- Obtaining the W (estimated unwanted variation factors).',
            color = 'blue',
            verbose = verbose
            )
        W <- Y.stand[, ncg.set] %*% t(ac) %*% solve(ac %*% t(ac))
        ## obtaining normalized data for the maximum value of k ####
        printColoredMessage(
            message = '- Obtaining the normalized data for the maximum value of k:',
            color = 'blue',
            verbose = verbose
            )
        newY.max <- Y - W %*% alpha
        newY.max <- t(newY.max[1:ncol(se.obj) ,])
        newY.max <- list(newY = newY.max, W = W[1:ncol(se.obj) , , drop = FALSE])
        ## obtaining normalized data for other values of k ####
        other.k <- k.vals[!k.vals %in% max(k.vals)]
        printColoredMessage(
            message = '- Obtaining the normalized data for other values of k:',
            color = 'blue',
            verbose = verbose
            )
        all.ruv <- lapply(
            other.k,
            function(y) {
                alpha <- t(left.sing.value[ , 1:y, drop = FALSE]) %*% Y
                ac <- alpha[, ncg.set, drop = FALSE]
                W <- Y.stand[, ncg.set] %*% t(ac) %*% solve(ac %*% t(ac))
                Wa <- W %*% alpha
                newY <- Y - Wa
                newY <- t(newY[1:ncol(se.obj) , ])
                if (isFALSE(return.wa)){
                    return(list(
                        newY = newY,
                        W = W[1:ncol(se.obj) , , drop = FALSE])
                        )
                }
                if (isTRUE(return.wa)){
                    return(list(
                        newY = newY,
                        W = W[1:ncol(se.obj) , , drop = FALSE],
                        Wa = t(Wa[1:ncol(se.obj), ])
                        ))
                }
            })
        all.ruv[[length(k.vals)]] <- newY.max
        if (control.sample.types == 'prps'){
            names(all.ruv) <- paste0('RUVIIIprps_k_', k.vals)
        } else if (control.sample.types == 'tr'){
            names(all.ruv) <- paste0('RUVIIItr_k_', k.vals)
        } else if (control.sample.types == 'both'){
            names(all.ruv) <- paste0('RUVIIIprpstr_k_', k.vals)
        }
    }
    ## k == 1 ####
    if (length(k) == 1) {
        ### checking ncg ####
        ncg.set <- final.ncg
        ncg.logi <- rep(FALSE, nrow(se.obj))
        ncg.logi[ncg.set] <- TRUE
        ncg.set <- ncg.logi
        ## checking control samples data ####
        prps.data <- prps.data
        k.vals <- k
        ## merging data and control samples ####
        Y <- t(cbind(Y, prps.data))
        if (is.data.frame(Y))
            Y <- data.matrix(Y)
        if (sum(is.na(Y)) > 0) {
            stop("The assay or PRPS data contains missing values. This is not supported.")
        } else if (sum(Y == Inf, na.rm = TRUE) + sum(Y == -Inf, na.rm = TRUE) > 0) {
            stop("The assay or PRPS data contains infinity values. This is not supported.")
        }
        ## applying RUV1 ####
        printColoredMessage(
            message = '- Applying RUV1 on both assay and control samples:',
            color = 'blue',
            verbose = verbose
            )
        Y <- RUV1(
            Y = Y,
            eta = eta,
            ctl = ncg.set,
            include.intercept = include.intercept
            )
        ## standardizing data ####
        printColoredMessage(
            message = '- Standardizing the both data and control samples:',
            color = 'blue',
            verbose = verbose
            )
        Y.stand <- scale(Y, center = TRUE, scale = FALSE)
        ## creating M matrix ####
        printColoredMessage(
            message = '- Creating the M matrix (replication patterns):',
            color = 'blue',
            verbose = verbose
            )
        M <- replicate.matrix(row.names(Y))
        ## applying a sanity check on the M matrix ####
        printColoredMessage(
            message = '- Applying a sanity check on the M matrix:',
            color = 'blue',
            verbose = verbose
            )
        sum(rowSums(M) != 1)
        sum(colSums(M) == 1)
        ## obtaining residuals from the PRPS sets ####
        printColoredMessage(
            message = '- Obtaining residuals from the control samples:',
            color = 'blue',
            verbose = verbose
            )
        Y0 <- fastResidop2(Y, M)
        ## applying svd on the residuals and the obtain alpha ####
        printColoredMessage(
            message = '- Applying svd on the residuals to obtain full alpha:',
            color = 'blue',
            verbose = verbose
            )
        left.sing.value <- BiocSingular::runSVD(
            x = Y0,
            k = max(k.vals),
            BSPARAM = bsparam(),
            center = FALSE,
            scale = FALSE
            )$u
        alpha <- t(left.sing.value[, 1:k.vals, drop = FALSE]) %*% Y
        ac <- alpha[, ncg.set, drop = FALSE]
        ## obtaining  W ####
        printColoredMessage(
            message = '- Obtaining the estimated unwanted factors,  W :',
            color = 'blue',
            verbose = verbose
            )
        W <- Y.stand[, ncg.set] %*% t(ac) %*% solve(ac %*% t(ac))
        ## obtaining normalized data ####
        printColoredMessage(
            message = '- Obtaining RUV-III normalized data:',
            color = 'blue',
            verbose = verbose
            )
        newY <- Y - W %*% alpha
        newY <- t(newY[1:ncol(se.obj) ,])
        all.ruv <- list(newY = newY, W = W[1:ncol(se.obj) , , drop = FALSE])
        if (is.null(output.name))  output.name <- paste0('RUVIIIprps_k_', k.vals)
    }

    # Saving data sets and W ####
    printColoredMessage(
        message = '-- Saving all the RUV-III normalized data and W matrix:',
        color = 'magenta',
        verbose = verbose)

    ## saving the norm data into a new assay ####
    if (isTRUE(save.se.obj)) {
        printColoredMessage(
            message = '- Add all the RUV-III normalized as new assay to the SummarizedExperiment object:',
            color = 'blue',
            verbose = verbose)
        if (length(k) == 1){
            newY <- all.ruv$newY
            colnames(newY) <- colnames(se.obj)
            se.obj@assays@data[[output.name]] <- newY
        } else{
            for (x in 1:length(all.ruv)) {
                newY <- all.ruv[[x]]$newY
                colnames(newY) <- colnames(se.obj)
                se.obj@assays@data[[names(all.ruv[x])]] <- newY
            }
        }
        # saving the W and alpha as well ####
        if (isTRUE(return.w)) {
            # check if RUVIII already exists in the metadata
            if (length(se.obj@metadata) == 0) {
                se.obj@metadata[['RUVIII']] <- list()
            }
            # check if RUVIII already exists in the metadata
            if (!'RUVIII' %in% names(se.obj@metadata)) {
                se.obj@metadata[['RUVIII']] <- list()
            }
            ## check if W already exists in the RUVIII
            if (!'W' %in% names(se.obj@metadata[['RUVIII']])) {
                se.obj@metadata[['RUVIII']][['W']] <- list()
            }
            if (length(k) == 1){
                if (!output.name %in% names(se.obj@metadata[['RUVIII']][['W']])) {
                    se.obj@metadata[['RUVIII']][['W']][[output.name]] <- list()
                }
                se.obj@metadata[['RUVIII']][['W']][[output.name]] <- all.ruv$W
            } else if (length(k) > 1){
                for(x in 1:length(all.ruv)){
                    output.name <- names(all.ruv[x])
                    ## Check if metadata RUVIII already exist for this assay
                    if (!output.name %in% names(se.obj@metadata[['RUVIII']][['W']])) {
                        se.obj@metadata[['RUVIII']][['W']][[output.name]] <- list()
                    }
                    se.obj@metadata[['RUVIII']][['W']][[output.name]] <- all.ruv[[x]]$W
                }
            }
        }
        # saving the WA and alpha as well ####
        if (isTRUE(return.wa)) {
            # check if RUVIII already exists in the metadata
            if (length(se.obj@metadata) == 0) {
                se.obj@metadata[['RUVIII']] <- list()
            }
            # check if RUVIII already exists in the metadata
            if (!'RUVIII' %in% names(se.obj@metadata)) {
                se.obj@metadata[['RUVIII']] <- list()
            }
            ## check if W already exists in the RUVIII
            if (!'W' %in% names(se.obj@metadata[['RUVIII']])) {
                se.obj@metadata[['RUVIII']][['Wa']] <- list()
            }
            if (length(k) == 1){
                if (!output.name %in% names(se.obj@metadata[['RUVIII']][['Wa']])) {
                    se.obj@metadata[['RUVIII']][['Wa']][[output.name]] <- list()
                }
                se.obj@metadata[['RUVIII']][['Wa']][[output.name]] <- all.ruv$Wa
            } else if (length(k) > 1){
                for(x in 1:length(all.ruv)){
                    output.name <- names(all.ruv[x])
                    ## Check if metadata RUVIII already exist for this assay
                    if (!output.name %in% names(se.obj@metadata[['RUVIII']][['W']])) {
                        se.obj@metadata[['RUVIII']][['Wa']][[output.name]] <- list()
                    }
                    se.obj@metadata[['RUVIII']][['Wa']][[output.name]] <- all.ruv[[x]]$Wa
                }
            }
        }
        printColoredMessage(message = '------------The RUVIIIprps function finished.',
                            color = 'white',
                            verbose = verbose)
        return(se.obj)
    } else if (!return.w & !save.se.obj) {
        printColoredMessage(message = '------------The RUVIIIprps function finished.',
                            color = 'white',
                            verbose = verbose)
        return(all.ruv)
    } else if (return.w & !save.se.obj) {
        printColoredMessage(message = '------------The RUVIIIprps function finished.',
                            color = 'white',
                            verbose = verbose)
        return(all.ruv)
    }
}
